POST http://localhost:3000/api/merchants HTTP/1.1
content-type: application/json

{
    "name": "merchant1",
    "password": "passmerchant1",
    "address": "london street",
    "phone_number":"+12345678"
}
###
GET http://localhost:3000/api/merchants HTTP/1.1
content-type: application/json
###

GET http://localhost:3000/api/merchants/1 HTTP/1.1
content-type: application/json
###

DELETE http://localhost:3000/api/merchants/2 HTTP/1.1
content-type: application/json